// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package customers

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitCustomerApi(db *gorm.DB) CustomerApi {
	customerRepository := ProvideCustomerRepository(db)
	customerService := ProvideCustomerService(customerRepository)
	customerApi := ProvideCustomerApi(customerService)
	return customerApi
}
