// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package suppliers

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitSupplierApi(db *gorm.DB) SupplierAPI {
	supplierRepository := ProvideSupplierRepository(db)
	supplierService := ProvideSupplierService(supplierRepository)
	supplierAPI := ProvideSupplierApi(supplierService)
	return supplierAPI
}
