// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package invoices

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitInvoiceApi(db *gorm.DB) InvoiceApi {
	invoiceRepository := ProvideInvoiceRepository(db)
	invoiceService := ProvideInvoiceService(invoiceRepository)
	invoiceApi := ProvideInvoiceApi(invoiceService)
	return invoiceApi
}
