// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package products

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitProductApi(db *gorm.DB) ProductApi {
	productRepository := ProvideProductRepository(db)
	productService := ProvideProductService(productRepository)
	productApi := ProvideProductApi(productService)
	return productApi
}
